README.md, pom.xml, src/main/resources/openapi/schemas/tenantAttributes.json
=> FOLIO-722 initial repo setup

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/java/org/folio/tlib/api/Tenant2Api.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java, src/test/java/org/folio/tlib/api/Tenant2ApiTest.java
Adding basic steps for creating tables for eusage.
=> Check for existing database schema

src/main/java/org/folio/tlib/api/Tenant2Api.java, src/test/java/org/folio/tlib/api/Tenant2ApiTest.java
Log DB_PORT, DB_HOST on connection refused to Postgres
=> Catch connection refused specifically and log env

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/java/org/folio/tlib/api/Tenant2Api.java, src/main/resources/openapi/eusage-reports-1.0.yaml, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
GET /eusage-reports/report-titles may be limited to those
associated with specific counter report.
=> Query parameter counterReportId

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java
Stream would hang if more than 50 rows returned, due to connection
being closed before transaction was complete.
=> Fix stream handling

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
Get invoicedCost by lookup /invoice-storage/invoices by poLineId.
=> Get invoicedCost

descriptors/ModuleDescriptor-template.json
@adamdickmeiss Does this look right?
=> Module descriptor extended to support POST to report-titles

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
Get fiscal year by following the relations: poline, fund, ledger, fiscal_year.
=> Populate fiscal year range MODEUR-24

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/resources/openapi/schemas/reportTitle.json, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
The new - all optional - properties are:
printISSN, onlineISSN, ISBN, DOI
=> Extend title entries with identifiers MODEUR-27

descriptors/ModuleDescriptor-template.json
Getting fiscal year information involves querying mod-finance-storage.
Update the module descriptor accordingly.
=> Module descriptor updates for MODEUR-24 work

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java
Due to premature connection close.
=> Fix limit failure

src/main/resources/openapi/eusage-reports-1.0.yaml, src/main/resources/openapi/parameters/agreement-id.yaml, src/main/resources/openapi/parameters/end-date.yaml, src/main/resources/openapi/parameters/format.yaml, src/main/resources/openapi/parameters/include-oa.yaml, src/main/resources/openapi/parameters/period-of-use.yaml, src/main/resources/openapi/parameters/start-date.yaml
The item returned for each of the 4 services is not defined yet.
=> openapi spec for stored reports

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/resources/openapi/schemas/reportTitle.json, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
kbManualMatch was always set to TRUE before and therefore did not
allowed unignoring a title.
=> Honor kbManualMatch in post titles MODEUR-37

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
If not sharing, the parallel handling, will result in Timeout on
getting a free connection.
=> Shared SQL connection for parsing counter reports

src/main/java/org/folio/tlib/api/Tenant2Api.java, src/test/java/org/folio/tlib/api/ApiIT.java, src/test/java/org/folio/tlib/api/Tenant2ApiTest.java
This fixes failures like this:
https://jenkins-aws.indexdata.com/blue/organizations/jenkins/folio-org%2Fmod-eusage-reports/detail/master/46/pipeline
https://jenkins-aws.indexdata.com/job/folio-org/job/mod-eusage-reports/job/MODEUR-14-book-report/2/execution/node/53/log/
=> MODEUR-14: Wait until POST /_/tenant completes

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
Property "YOP" value - YYYY - will be converted to YYYY-01-01.
Property "Publication_Date" is used as first precedence
as it is of more specific format YYYY-MM-DD.
=> Parse YOP from counter reports MODEUR-46

pom.xml, src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/resources/openapi/eusage-reports-1.0.yaml, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java, src/test/java/org/folio/tlib/api/ApiIT.java
This adds three service:
* `/eusage-reports/stored-reports/use-over-time/csv` 
* `/eusage-reports/stored-reports/reqs-by-date-of-use/csv`
* `/eusage-reports/stored-reports/reqs-by-pub-year/csv`
=> CSV reporting MODEUR-15 MODEUR-18

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/resources/openapi/schemas/report.json, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
ByPeriod reporting MODEUR-50 MODEUR-53
totalRequestsPublicationYearsByPeriod and uniqueRequestsPublicationYearsByPeriod for the
reqsByDateOfUse report.
totalRequestPeriodsOfUseByPeriod and uniqueRequestPeriodsOfUseByPeriod for the
reqsByPubYear report.
=> ByPeriod reporting MODEUR-50 MODEUR-53

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
=> Get counter reports in chunks MODEUR-70

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/java/org/folio/eusage/reports/api/Periods.java, src/main/java/org/folio/eusage/reports/api/ReqsByDateOfUse.java, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
One simple SQL query and move some work to Java.
=> Fix getReqsByDateOfUse slow MODEUR-75

src/main/java/org/folio/eusage/reports/api/Periods.java, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
=> Loosen 10 year period restriction MODEUR-72

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/java/org/folio/eusage/reports/api/ReqsByDateOfUse.java, src/main/java/org/folio/eusage/reports/api/ReqsByPubYear.java, src/main/java/org/folio/eusage/reports/api/UseOverTime.java, src/main/resources/openapi/schemas/reportTitle.json, src/test/java/org/folio/eusage/reports/MainVerticleTest.java, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
Quite big PR which also re-implements useOverTime to use same strategy for reporting as reqsByPubYear and reqsByDateOfUse for smaller code base and faster processing time.
=> Publication type MODEUR-82

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java
This speeds up processing of counter reports.
=> Create index for counterReportTitle

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/java/org/folio/eusage/reports/api/ReqsByDateOfUse.java, src/main/java/org/folio/eusage/reports/api/ReqsByPubYear.java, src/main/java/org/folio/eusage/reports/api/UseOverTime.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
reqsByPubYear and reqsByDateOfUse to include non-matched titles -
including non-matched in counter reports, outside periods etc -
ALL titles part of the agreement.
=> reqsBy{PubYear,DateOfUse} includes all titles MODEUR-92

src/main/java/org/folio/eusage/reports/api/CostPerUse.java, src/main/java/org/folio/eusage/reports/api/DateRange.java, src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/main/java/org/folio/eusage/reports/api/UseOverTime.java, src/main/resources/openapi/schemas/reportCost.json, src/test/java/org/folio/eusage/reports/api/DateRangeTest.java, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
Dividing by title count in package. Divide cost for title in by period of which it is analyzed.
=> Reimplement CostPerUse MODEUR-94

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
Using amount in transation https://github.com/folio-org/acq-models/blob/master/mod-finance/schemas/transaction.json
=> Fix encumbrances not parsed right MODEUR-105

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
https://issues.folio.org/browse/MODEUR-116
=> ERM paging MODEUR-116

src/main/java/org/folio/eusage/reports/api/CostPerUse.java, src/main/java/org/folio/eusage/reports/api/UseOverTime.java
https://issues.folio.org/browse/MODEUR-117
=> Reduce logging MODEUR-117

src/main/java/org/folio/eusage/reports/api/CostPerUse.java, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
And fix amountEncumbered for not being set in title entries.
=> Omit titles wo shared periods MODEUR-119

README.md, pom.xml, src/main/java/org/folio/eusage/reports/MainVerticle.java, src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
https://issues.folio.org/browse/MODEUR-128
=> Use folio-vertx-lib 1.0.0 MODEUR-128

NEWS.md, pom.xml
Note - next release is 1.1.1-SNAPSHOT in master.
=> Release 1.1.0 MODEUR-129

pom.xml, src/main/java/org/folio/tlib/util/TenantUtil.java, src/test/java/org/folio/tlib/util/TenantUtilTest.java
This PR is for 1.0 series only (where folio-vertx-lib was not split out).
=> Allow tenants with suffix _ and digits MODEUR-130

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/MainVerticleTest.java
=> Use TenantUtil.tenant

pom.xml
Upgrade also to okapi 4.14, folio-vertx-lib 1.1.0, rest-assured 4.5.1,
testcontainers 1.17.1.
=> Upgrade to Vert.x 4.2.7, log4j 2.17.2 .. MODEUR-133

src/main/java/org/folio/eusage/reports/api/EusageReportsApi.java, src/test/java/org/folio/eusage/reports/api/EusageReportsApiTest.java
The publicationType in ERM may hold "journal" as well as "serial".
=> Fix no graphs with GOKb titles MODEUR-139

.github/workflows/api-doc.yml, Jenkinsfile, src/main/resources/openapi/eusage-reports-1.0.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflow for api-doc
(instead of Jenkins-operated CI stage).
https://dev.folio.org/guides/api-doc/
=> FOLIO-3678 Use GitHub Workflow api-doc

src/main/resources/openapi/eusage-reports-1.0.yaml
Fix to suddenly broken folio-tools/api-doc dependency.
=> FOLIO-3678 Verify GitHub Workflow api-doc

Dockerfile, Jenkinsfile, pom.xml
=> MODEUR-149-update-to-java-17

pom.xml
=> MODEUR-152

NEWS.md, pom.xml
=> MODEUR-151

pom.xml
and update some other dependencies as well
=> [MODEUR-153] Update to folio-vertx-lib v3.2.0, Vert.x v4.5.4

descriptors/ModuleDescriptor-template.json, pom.xml
[APPDESCRIP-28](https://folio-org.atlassian.net/browse/APPDESCRIP-28)
Related PR: https://github.com/folio-org/app-erm-usage/pull/1
Purpose: update erm-usage/files interface id to be valid for Eureka platform
=> APPDESCRIP-28: update erm-usage/files interface id to be valid for Eureka platform

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODEUR-159
See https://github.com/folio-org/mod-erm-usage/pull/184
=> Add support for counter-reports interface 4.0

.github/workflows/postgres.yml, pom.xml, src/test/java/org/folio/eusage/reports/BasicDbTest.java
https://folio-org.atlassian.net/browse/MODEUR-160
- Updates `folio-vertx-lib` to `v3.3.0`
- Adds GA workflow for postgres
=> [MODEUR-160] Update folio-vertx-lib to v3.3.0

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/MODEUR-161
Release v3.0.0
=> [MODEUR-161] Release v3.0.0

Dockerfile, Jenkinsfile, pom.xml
https://folio-org.atlassian.net/browse/MODEUR-162
* Upgrades to Java 21
* Updates maven dependencies to recent versions
=> [MODEUR-162] Upgrade to Java 21
